### ISSUE TITLE
Singlem error with DIAMOND

### ISSUE THREAD

**Issue by Rainjie-afk** [wwood/singlem#122]
Hellow wwood, I successfully installed the software Singlem and specified the database path, but when I run it in command line, it prompts that DIAMOND failed. Is it because my computer doesn't have enough memory to run DIAMOND or how can I solve this problem?"

This is my error information.

(singlem) hyj@hyj:/media/hyj/E/singlem-main/bin$ singlem pipe -1 /media/hyj/F/ProjectZLP/2U/ERR1600539_1.fastq.gz -2 /media/hyj/F/ProjectZLP/2U/ERR1600539_2.fastq.gz --otu-table /media/hyj/F/ProjectZLP/2U/1.tsv  --threads 8

02/25/2023 03:25:12 AM INFO: SingleM v1.0.0beta5

02/25/2023 03:25:12 AM INFO: Retrieval successful. Location of backpack is: /media/hyj/E/Database/Singlem_DB/S3.1.0.metapackage_20221209.smpkg.zb

02/25/2023 03:25:12 AM INFO: Loaded 59 SingleM packages

02/25/2023 03:25:12 AM INFO: Using as input 1 different pairs of sequence files e.g. /media/hyj/F/ProjectZLP/2U/ERR1600539_1.fastq.gz & /media/hyj/F/ProjectZLP/2U/ERR1600539_2.fastq.gz

02/25/2023 03:25:12 AM INFO: Filtering sequence files through DIAMOND blastx

02/25/2023 03:26:05 AM ERROR: Process (DIAMOND?) failed

Traceback (most recent call last):

  File "/media/hyj/E/singlem-main/bin/singlem", line 591, in <module>

    singlem.pipe.SearchPipe().run(

  File "/media/hyj/E/singlem-main/bin/../singlem/pipe.py", line 63, in run

    otu_table_object = self.run_to_otu_table(**kwargs)

                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/media/hyj/E/singlem-main/bin/../singlem/pipe.py", line 334, in run_to_otu_table

    raise e

  File "/media/hyj/E/singlem-main/bin/../singlem/pipe.py", line 327, in run_to_otu_table

    self._num_threads, self._working_directory).run_diamond(

                                                ^^^^^^^^^^^^

  File "/media/hyj/E/singlem-main/bin/../singlem/diamond_spkg_searcher.py", line 34, in run_diamond

    fwds = self._prefilter(dmnd, forward_read_files, False, performance_parameters)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/media/hyj/E/singlem-main/bin/../singlem/diamond_spkg_searcher.py", line 94, in _prefilter

    qseqid_sseqid = extern.run(cmd)

                    ^^^^^^^^^^^^^^^

  File "/home/hyj/miniconda3/envs/singlem/lib/python3.11/site-packages/extern/__init__.py", line 41, in run

    raise ExternCalledProcessError(process, command)

extern.ExternCalledProcessError: Command diamond blastx --outfmt 6 qseqid full_qseq sseqid --max-target-seqs 1 --evalue 0.01 --block-size 0.5 --target-indexed -c1 --min-orf 24 --threads 8 --query /media/hyj/F/ProjectZLP/2U/ERR1600539_1.fastq.gz --db /media/hyj/E/Database/Singlem_DB/S3.1.0.metapackage_20221209.smpkg.zb/payload_directory/prefilter.fna.dmnd | tee >(sed 's/^/>/; s/\t/\n/; s/\t.*//' > /tmp/tmp9c2d3ibn/prefilter_forward/ERR1600539_1.fna) | awk '{print $1,$3}' returned non-zero exit status 139.

STDERR was: b"bash\xef\xbc\x9a\xe8\xa1\x8c 1: 37997 \xe6\xae\xb5\xe9\x94\x99\xe8\xaf\xaf               \xef\xbc\x88\xe6\xa0\xb8\xe5\xbf\x83\xe5\xb7\xb2\xe8\xbd\xac\xe5\x82\xa8\xef\xbc\x89 diamond blastx --outfmt 6 qseqid full_qseq sseqid --max-target-seqs 1 --evalue 0.01 --block-size 0.5 --target-indexed -c1 --min-orf 24 --threads 8 --query /media/hyj/F/ProjectZLP/2U/ERR1600539_1.fastq.gz --db /media/hyj/E/Database/Singlem_DB/S3.1.0.metapackage_20221209.smpkg.zb/payload_directory/prefilter.fna.dmnd\n     37998 \xe5\xb7\xb2\xe5\xae\x8c\xe6\x88\x90               | tee >(sed 's/^/>/; s/\\t/\\n/; s/\\t.*//' > /tmp/tmp9c2d3ibn/prefilter_forward/ERR1600539_1.fna)\n     37999 \xe5\xb7\xb2\xe5\xae\x8c\xe6\x88\x90               | awk '{print $1,$3}'\n"STDOUT was: b''

**When I tested DIAMOND in the singlme environment, the error message was.**
(singlem) hyj@hyj:/media/hyj/E/singlem-main/bin$ diamond blastx --outfmt 6 qseqid full_qseq sseqid --max-target-seqs 1 --evalue 0.01 --block-size 0.5 --target-indexed -c1 --min-orf 24 --threads 7 --query /media/hyj/E/NAFLD_PRJNA373901/data/Metawrap_binning/SRR5275397/metabat2_bins/bin.3.fa --db /media/hyj/E/Database/Singlem_DB/S3.1.0.metapackage_20221209.smpkg.zb/payload_directory/prefilter.fna.dmnd --out /media/hyj/E/NAFLD_PRJNA373901/data/Metawrap_binning/SRR5275397/metabat2_bins/bin.3.fa.otu
diamond v2.1.3.157 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 7
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /media/hyj/E/NAFLD_PRJNA373901/data/Metawrap_binning/SRR5275397/metabat2_bins
#Target sequences to report alignments for: 1
Opening the database...  [0.006s]
Database: /media/hyj/E/Database/Singlem_DB/S3.1.0.metapackage_20221209.smpkg.zb/payload_directory/prefilter.fna.dmnd (type: Diamond database, sequences: 65337, letters: 5095531)
Block size = 500000000
Algorithm: Double-indexed
Loading reference sequences...  [0.011s]
Masking reference...  [0.06s]
Initializing temporary storage...  [0.005s]
Building reference histograms...  [0.029s]
Allocating buffers... 段错误 (核心已转储)

Many thanks

**Comment by wwood** [comment]
Hi,

Thanks for trying singlem. I think that error is caused by a packaging error in a newly released diamond. Try diamond <2.1 ?

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
From: Rainjie-afk ***@***.***>
Sent: Saturday, February 25, 2023 3:52:26 PM
To: wwood/singlem ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwood/singlem] Singlem error with (Issue #122)


Hellow wwood, I successfully installed the software Singlem and specified the database path, but when I run it in commond line, it prompts that diamond failed. Is it because my computer doesn't have enough memory to run software B? Or how can I solve this problem?"

This is my error imformation.

(singlem) ***@***.***:/media/hyj/E/singlem-main/bin$ singlem pipe -1 /media/hyj/F/ProjectZLP/2U/ERR1600539_1.fastq.gz -2 /media/hyj/F/ProjectZLP/2U/ERR1600539_2.fastq.gz --otu-table /media/hyj/F/ProjectZLP/2U/1.tsv --threads 8

02/25/2023 03:25:12 AM INFO: SingleM v1.0.0beta5

02/25/2023 03:25:12 AM INFO: Retrieval successful. Location of backpack is: /media/hyj/E/Database/Singlem_DB/S3.1.0.metapackage_20221209.smpkg.zb

02/25/2023 03:25:12 AM INFO: Loaded 59 SingleM packages

02/25/2023 03:25:12 AM INFO: Using as input 1 different pairs of sequence files e.g. /media/hyj/F/ProjectZLP/2U/ERR1600539_1.fastq.gz & /media/hyj/F/ProjectZLP/2U/ERR1600539_2.fastq.gz

02/25/2023 03:25:12 AM INFO: Filtering sequence files through DIAMOND blastx

02/25/2023 03:26:05 AM ERROR: Process (DIAMOND?) failed

Traceback (most recent call last):

File "/media/hyj/E/singlem-main/bin/singlem", line 591, in

singlem.pipe.SearchPipe().run(



File "/media/hyj/E/singlem-main/bin/../singlem/pipe.py", line 63, in run

otu_table_object = self.run_to_otu_table(**kwargs)



                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



File "/media/hyj/E/singlem-main/bin/../singlem/pipe.py", line 334, in run_to_otu_table

raise e



File "/media/hyj/E/singlem-main/bin/../singlem/pipe.py", line 327, in run_to_otu_table

self._num_threads, self._working_directory).run_diamond(



                                            ^^^^^^^^^^^^



File "/media/hyj/E/singlem-main/bin/../singlem/diamond_spkg_searcher.py", line 34, in run_diamond

fwds = self._prefilter(dmnd, forward_read_files, False, performance_parameters)



       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



File "/media/hyj/E/singlem-main/bin/../singlem/diamond_spkg_searcher.py", line 94, in _prefilter

qseqid_sseqid = extern.run(cmd)



                ^^^^^^^^^^^^^^^



File "/home/hyj/miniconda3/envs/singlem/lib/python3.11/site-packages/extern/init.py", line 41, in run

raise ExternCalledProcessError(process, command)



extern.ExternCalledProcessError: Command diamond blastx --outfmt 6 qseqid full_qseq sseqid --max-target-seqs 1 --evalue 0.01 --block-size 0.5 --target-indexed -c1 --min-orf 24 --threads 8 --query /media/hyj/F/ProjectZLP/2U/ERR1600539_1.fastq.gz --db /media/hyj/E/Database/Singlem_DB/S3.1.0.metapackage_20221209.smpkg.zb/payload_directory/prefilter.fna.dmnd | tee >(sed 's/^/>/; s/\t/\n/; s/\t.*//' > /tmp/tmp9c2d3ibn/prefilter_forward/ERR1600539_1.fna) | awk '{print $1,$3}' returned non-zero exit status 139.

STDERR was: b"bash\xef\xbc\x9a\xe8\xa1\x8c 1: 37997 \xe6\xae\xb5\xe9\x94\x99\xe8\xaf\xaf \xef\xbc\x88\xe6\xa0\xb8\xe5\xbf\x83\xe5\xb7\xb2\xe8\xbd\xac\xe5\x82\xa8\xef\xbc\x89 diamond blastx --outfmt 6 qseqid full_qseq sseqid --max-target-seqs 1 --evalue 0.01 --block-size 0.5 --target-indexed -c1 --min-orf 24 --threads 8 --query /media/hyj/F/ProjectZLP/2U/ERR1600539_1.fastq.gz --db /media/hyj/E/Database/Singlem_DB/S3.1.0.metapackage_20221209.smpkg.zb/payload_directory/prefilter.fna.dmnd\n 37998 \xe5\xb7\xb2\xe5\xae\x8c\xe6\x88\x90 | tee >(sed 's/^/>/; s/\t/\n/; s/\t.*//' > /tmp/tmp9c2d3ibn/prefilter_forward/ERR1600539_1.fna)\n 37999 \xe5\xb7\xb2\xe5\xae\x8c\xe6\x88\x90 | awk '{print $1,$3}'\n"STDOUT was: b''

When I tested DIAMOND in the singlme environment, the error message was.
(singlem) ***@***.***:/media/hyj/E/singlem-main/bin$ diamond blastx --outfmt 6 qseqid full_qseq sseqid --max-target-seqs 1 --evalue 0.01 --block-size 0.5 --target-indexed -c1 --min-orf 24 --threads 7 --query /media/hyj/E/NAFLD_PRJNA373901/data/Metawrap_binning/SRR5275397/metabat2_bins/bin.3.fa --db /media/hyj/E/Database/Singlem_DB/S3.1.0.metapackage_20221209.smpkg.zb/payload_directory/prefilter.fna.dmnd --out /media/hyj/E/NAFLD_PRJNA373901/data/Metawrap_binning/SRR5275397/metabat2_bins/bin.3.fa.otu
diamond v2.1.3.157 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 7
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /media/hyj/E/NAFLD_PRJNA373901/data/Metawrap_binning/SRR5275397/metabat2_bins
#Target sequences to report alignments for: 1
Opening the database... [0.006s]
Database: /media/hyj/E/Database/Singlem_DB/S3.1.0.metapackage_20221209.smpkg.zb/payload_directory/prefilter.fna.dmnd (type: Diamond database, sequences: 65337, letters: 5095531)
Block size = 500000000
Algorithm: Double-indexed
Loading reference sequences... [0.011s]
Masking reference... [0.06s]
Initializing temporary storage... [0.005s]
Building reference histograms... [0.029s]
Allocating buffers... 段错误 (核心已转储)

Many thanks

―

**Comment by Rainjie-afk** [comment]
Many thanks for your advice. I was able to run singlem successfully by modifying version DIAMOND VERSION 2.1.3 to 2.0.15.

Thanks again for all the software you have developed for metagenomic analysis.

**Comment by wwood** [comment]
Glad to hear it, and thanks for kind words
