### ISSUE TITLE
Are SingleM-defined OTUs variable or identical in the 60-base target window

### ISSUE THREAD

**Issue by Virginia-Rich** [wwood/singlem#128]
Hi @wwood !  I just wanted to check I understand something fundamental about SingleM's OTUs:  unless one applies the -cluster function, each OTU only contains sequences that are identical across the entire 60-base search window, correct? They will be of heterogeneous length (and likely sequence identity) either side, but identical in their target window?  Thanks so much!

**Comment by wwood** [comment]
Hi Gin,

Yes, that's right. By default, OTUs are 100% clustered within the 60bp, but may differ outside of that.

Actually no attempt is made to align the sequences outside of the window. I would think in many cases they will identically align to each other since they are often from the same species, but not always, but depends on the specific OTU.

Let me know if there is anything else.

**Comment by Virginia-Rich** [comment]
Awesome thanks Ben, that's very helpful confirmation!
