### ISSUE TITLE
Benchmark between singleM and mOTUS?

### ISSUE THREAD

**Issue by Ge0rges** [wwood/singlem#143]
Hello,

I was wondering if there exists a benchmark of singleM against other popular similar tools such as mOTUs? As an aside, which paper should be cited if we used singleM?

**Comment by wwood** [comment]
Hi,

We are working on a paper, which includes benchmarks - draft done, now editing, so hope that will come out soon to biorxiv.

In those benchmarks SingleM does better that other tested tools, particularly when there's novel lineages present or in complex communities.

I'm closing this since it isn't useful as a way of tracking - working on the paper already..
