### ISSUE TITLE
can you convert between regular and archive format?

### ISSUE THREAD

**Issue by rrohwer** [wwood/singlem#152]
I have to run `singlem pipe` separately because I have too many files for a combined run, but then I have to combine them sequentially because the singlem commands cannot accept that many file arguments (I get an error about a bash command being too long!). This works if I generate standard OTU table files, for example:

```
$ singlem pipe --genome-fasta-files testsinglem/bin132.fna --otu-table test132.csv --threads 1
$ singlem pipe --genome-fasta-files testsinglem/bin15.fna --otu-table test15.csv --threads 1
$ singlem pipe --genome-fasta-files testsinglem/bin89.fna --otu-table test89.csv --threads 1
$ singlem summarise --input-otu-tables test132.csv test15.csv --output-otu-table partial_combo.csv
$ singlem summarise --input-otu-tables partial_combo.csv test89.csv --output-otu-table combo.csv
```

However the problem is that I want to use `singlem condense` and that only accepts archive OTU tables. And if I export archive otu tables from pipe, like:
```
$ singlem pipe --genome-fasta-files bin132.fna --archive-otu-table arch132.csv --threads 1
$ singlem pipe --genome-fasta-files bin15.fna --archive-otu-table arch15.csv --threads 1
$ singlem pipe --genome-fasta-files bin89.fna --archive-otu-table arch89.csv --threads 1
```

Summarize is no longer able to combine them! 
```
$ singlem summarise --input-archive-otu-tables arch132.csv arch15.csv --output-archive-otu-table partial_arch.csv
Exception: --output-archive-otu-table requires --collapse-to-sample-name to be defined. Some other transfomations have output archive tables, but they are specified separately.
```

But I don't want to transform the data (I don't fully understand what the collapse to sample name does), I simply want to combine the tables into a single file so that the commands will not break and the server admin will not yell at me for having more than 1000 files in a folder. 

So is there a way to convert to the archive json format to use `condense` after running pipe and summarize commands with regular otu tables? Or is there another workflow you recommend?

Thanks so much!

Robin

**Comment by wwood** [comment]
Hi Robin,

You cannot use regular OTU tables as input to condense, because they do not contain enough information.

You can get around this problem perhaps most easily by just specifying `-p` when originally running `pipe` - it'll then run condense for you. I'll add a note in the docs about this.

Combining archive OTU tables isn't currently supported, though doing so seems possible given some extra coding - PRs welcome. 

You can't convert regular OTU tables into archive OTU tables because there's not enough info in them. So you can't run condense starting with a regular OTU table.

If you don't want to rerun pipe - I guess that might incur some more CPU time - the easiest way would just be to run `condense` on each archive OTU table separately, and then combine the results of that. Combining those taxonomic profiles is easy enough - they are just 3 column TSV files so just concatenate them taking care of the headers. Again seems possible to implement something in `summarise` to do this but I haven't gotten around to it.

Let me know how you go.
ben
