### ISSUE TITLE
Question about taxonomic profile and combined files

### ISSUE THREAD

**Issue by susheelbhanu** [wwood/singlem#160]
Hi @wwood, 

I've managed to run singlem pipe and summarise. 

While the `otu` tables contain something the following, `d__Eukaryota; Fungi` and `d__Eukaryota; Metazoa`, this information is missing from the *taxonomic profile* files, and subsequently in the combined files. 

The profiles seem only to be limited to 'Bacteria' and 'Archaea'. Is there a way to retain the non-Bacteria/Archaea information in the profiles?

Thank you,
Susheel

**Comment by wwood** [comment]
Indeed, euks are excluded from the final profiles.

It is hard to include them because the genes are not single copy. We are working on a larger solution for this but it isn't a simple matter. 

There could be scope for including some note about them, being clear it is a qualitative rather than quantitative observation, though. I'll have a think.

**Comment by susheelbhanu** [comment]
Thanks for clarifying this!
