### ISSUE TITLE
Microbial fraction over 100%

### ISSUE THREAD

**Issue by kebow** [wwood/singlem#169]
I am getting a microbial fraction estimation over 100% for some samples. Are there any triggers that might cause this to happen? I'm running it on forward reads only and using seqkit generated base counts.
Thanks

**Comment by wwood** [comment]
Hi,

This is possible, and is usually due to simpler communities containing unknown lineages, because the genome sizes are based on genomes sizes of known taxa. How much over 100% are you getting? Do you get a warning that the estimate might be unreliable?

It might be possible to rescue by recovering genomes, and then inputting them into `singlem supplement` and rerunning `singlem microbial_fraction`.

**Comment by kebow** [comment]
At most I had 107%. The samples with the issue have very poor mapping rates to my genomes so it would make sense that there's something novel in there. I've deleted my log files unfortunately so not sure if there was a warning.

I reran with v0.16.0 (previously was using v1.0.0beta5) and now the fraction appears to be capped at 100%, which is much more satisfying! There's no warning for the affected samples. Running appraise now to see how they do.

**Comment by EisenRa** [comment]
Hi @kebow,

How did you go with supplement?
