### ISSUE TITLE
metapackage versioning error?

### ISSUE THREAD

**Issue by xvazquezc** [wwood/singlem#176]
Hi,

I was reinstalling/upgrading SingleM (to 0.16) and when downloading the metapackage with `singlem data` I noticed that the file reads `S3.1.2.GTDB_r207.metapackage_20240405.smpkg.zb.tar.gz`. It's odd as the last db version was 3.2.1 and r214. I just wanted to check if this is just a naming issue and not a mistake (i.e. wrong one uploaded).

Cheers

**Comment by wwood** [comment]
Hi Xabi,

Thanks for the report. It wasn't a clerical error but a misunderstanding about how zenodo works. 3.1.2 is a newer format but using older reference data. There's a new release of SingleM imminent that will fix this, but for now I suggest just downloading the 3.2.1 version from https://zenodo.org/records/8419620 and then using that as input using `--metapackage` after un-taring.

Closing since this is a dup of #175 

ben

**Comment by xvazquezc** [comment]
Thanks. Do you have any expected timeframe for the new release? I need to run quite a few analyses and might be worth to just wait for it...

**Comment by wwood** [comment]
Hey,

I would say within a week, if that helps. I think it is done already, just need to double check a few things and push it out.

**Comment by wwood** [comment]
The other thing is that there'll likely be an GTDB R220 database closely following, if you wanted to wait for that too.
