### ISSUE TITLE
Usable with metatranscriptomes?

### ISSUE THREAD

**Issue by AaronAOliver** [wwood/singlem#179]
Hello, thanks for the great tool (among many)!

Is it feasible to use SingleM to profile the relative abundance of marker genes in metatranscriptomes? I saw that Sandpiper specifically sorted out metatranscriptomic studies, but I couldn't tell if that was due to software limitations or to keep the number of included studies manageable.

Host RNA and all rRNA sequenced would be filtered out computationally beforehand, so the input would just be bacterial mRNA reads. Like your preprint showed, the other marker gene-based tools are terrible with taxa outside their databases, so they've performed poorly on our marine microbiomes. We've been using Kraken2 built off NCBI nr for the past few years, but the database has grown so much and requires so much disk space and memory that it will not be usable much longer for our group.

If SingleM doesn't work, maybe Kraken2 built off of GTDB is a better long-term solution for RNA studies?
Thanks!

**Comment by wwood** [comment]
Hi,

Thanks for the encouraging words.

Sandpiper filters out metaTs because SingleM isn't meant for analysis of them, SingleM would easily power through them (and wouldn't be affected by host RNA or rRNA).

I haven't had more than a half-hearted stab at applying SingleM to metaTs. I suppose your idea is to get a kind of community profile? In that case kraken would be answering a different question because there is presumably instances of highly expressed non-marker genes.

One thing to consider is that SingleM needs the insert sizes of the sequencing to be long enough. If it dips much below say 80bp (a rough guess), then the ORFs start to not be called and so marker gene reads are missed.

Anyway, I'm curious to see how you go.

**Comment by AaronAOliver** [comment]
Make sense! I will run some tests in the future to determine how SingleM can be incorporated into our pipelines in the future.
