### ISSUE TITLE
In OTU table, the same sequence can be assigned to 2 or more taxonomies

### ISSUE THREAD

**Issue by michoug** [wwood/singlem#28]
Hi,
When looking at the results of the OTU table, I realized that some "sequences" were assigned to different taxonomy. It's also happens after clustering. Ex:

```
gene	sample	sequence	num_hits	coverage	taxonomy
S1.13.ribosomal_protein_S15P_S13e	N5_F5	AAAGACAACCATTCCAGGCGTGGGCTACTGCAGATGGTGGCCGACAGGCACTCTCACATC	1	1.64	Root; d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Xanthomonadales; f__Xanthomonadaceae
S1.13.ribosomal_protein_S15P_S13e	N4_F4	AAAGACAACCATTCCAGGCGTGGGCTACTGCAGATGGTGGCCGACAGGCACTCTCACATC	1	3.28	Root; d__Bacteria; p__Firmicutes_A; c__Clostridia; o__Oscillospirales
S1.13.ribosomal_protein_S15P_S13e	N4_F5	AAAGACAACCATTCCAGGCGTGGGCTACTGCAGATGGTGGCCGACAGGCACTCTCACATC	1	1.64	Root; d__Bacteria; p__Proteobacteria; c__Alphaproteobacteria; o__Rhizobiales
```
Best
Greg

**Comment by wwood** [comment]
Hi,
This is possibly, at least technically, because taxonomy isn't assigned to just the window sequence. Instead, it is determined by summarising the taxonomy assigned to each read that makes up that OTU - each read is usually assigned taxonomy by GraftM (and pplacer/diamond) under the hood.

This is particularly a problem for clustering, in part because the taxonomy of each read is not recorded in the default `--otu_table` output of `pipe`. Usually when this kind of taxonomy difference happens the difference is not so stark as you are showing though. Can I ask, how was taxonomy assigned? Do you imagine that these OTUs are novel?

Thanks, ben
