### ISSUE TITLE
OTUs with no taxonomy

### ISSUE THREAD

**Issue by rachaellappan** [wwood/singlem#36]
Hi Ben,

I've encountered some cases where an OTU is not assigned any taxonomy and the last column is simply blank.

This is strange because that same OTU sequence can appear in more than one sample. In one sample, it receives a taxonomic assignment; but the same sequence in another sample receives none. Here's an example from a combined (all samples together) OTU table:

```
S1.10.ribosomal_protein_S7      S1-C-gD_qtrim_1 TATATGGTAATAGTAGATGTAAATGACCAAAAAAGATTTGATCAAGCCCTTGCTAACCTA    3       4.95    Root; d__Archaea; p__Crenarchaeota; c__Thermoprotei
S1.10.ribosomal_protein_S7      S4-C-gD_qtrim_1 TATATGGTAATAGTAGATGTAAATGACCAAAAAAGATTTGATCAAGCCCTTGCTAACCTA    1       1.65
```

This is a rare case (only 34 instances across all markers) and these are relieved by clustering the OTU table:

```
S1.10.ribosomal_protein_S7      S1-C-gD_qtrim_1 TATATGGTAATAGTAGATGTAAATGACCAAAAAAGATTTGATCAAGCCCTTGCTAACCTA    3       4.95    Root; d__Archaea; p__Crenarchaeota; c__Thermoprotei
S1.10.ribosomal_protein_S7      S4-C-gD_qtrim_1 TATATGGTAATAGTAGATGTAAATGACCAAAAAAGATTTGATCAAGCCCTTGCTAACCTA    1       1.65    Root; d__Archaea; p__Crenarchaeota; c__Thermoprotei
```

However, 23 of these 34 instances occur only once in one sample so remain without taxonomy after clustering.

Cheers,
Rachael

**Comment by wwood** [comment]
HI,

I've seen these before, they happen for a few reasons, but I'd overlooked them as being so rare that they weren't worth looking into. But, they would interfere during clustering because taxonomy of clusters is derived by taking a "median taxonomy" i.e. the parts of the taxonomy string that at least 50% of reads agree on.

It is reasonable (although annoyingly so) that the same OTU sequence from different samples is assigned different taxonomies, because taxonomy is assigned to the entirety of the underlying reads, not just the OTU sequence. Those reads are in all likelihood going to be different in each sample, so the taxonomy can change.

I'm not entirely sure of your circumstances, but probably for you the most appropriate thing to do would be just to remove sequences without taxonomy from the original outputs of 'pipe' and move forward from there.

Hope that makes sense.

**Comment by rachaellappan** [comment]
Makes sense, thanks Ben.

For anyone reading, you can check the number of OTUs that have no taxonomy like this (for example, in a combined OTU table that contains all samples):

```
# Count lines where the sixth column (taxonomy) is blank
cat combined_otu_table.tsv | awk '$6==""' | wc -l
```

And you can remove them with this:

```
# If the 6th column is blank, print the whole line into a new file
 cat combined_otu_table.tsv | awk '{if ($6) print $0;}' > new_table.tsv
```
