### ISSUE TITLE
Sequences in raw OTU table

### ISSUE THREAD

**Issue by pm-leung** [wwood/singlem#37]
Hi Ben,

Thanks for developing the amazing suite of M-tools! I've been trying to use SingleM to generate community profile from metagenomic data. Using the pipe command, SingleM generated an OTU table such as the one shown in the main page:

gene    sample  sequence        num_hits        coverage        taxonomy
4.21.ribosomal_protein_S19_rpsS my_sequences  TGGTCGCGCCGTTCGACGGTCACTCCGGACTTCATCGGCCTACAGTTCGCCGTGCACATC    1       1.64    Root; d__Bacteria; p__Proteobacteria; c__Deltaproteobacteria; o__Desulfuromonadales
4.21.ribosomal_protein_S19_rpsS my_sequences  TGGTCGCGGCGCTCAACCATTCTGCCCGAGTTCGTCGGCCACACCGTGGCCGTTCACAAC    1       1.64    Root; d__Bacteria; p__Acidobacteria; c__Solibacteres; o__Solibacterales; f__Solibacteraceae; g__Candidatus_Solibacter; s__Candidatus_Solibacter_usitatus

I wonder why sequences (column 3) from the table have only ~60 bp for all the markers and reads, given that each of the 14 single copy ribosomal markers should have gene length >250 bp and the usual input query read length is > 100bp. So, may you kindly share what the sequences in the OTU table means? Also, the subsequent OTU clustering steps use the raw table as an input, so I assumes the clustering is done with the 60ish bp sequences. Wouldn't the application of longer sequences works better for clustering purposes (at least allows a greater possible overlap between sequences)? If applicable, it will be ideal to see some basic principles behind SingleM somewhere, a manuscript on biorxiv for example. 

Many thanks,
PM

**Comment by wwood** [comment]
Hi PM, thanks for your interest an good question - you've clearly done your research.

You are right, only the 60bp sequences are used for all steps following, rather than all the reads that went into the OTU. You can record the sequence IDs that go into each OTU using `--output_extras` or by outputting the archive OTU table format, but that doesn't change the fact that they aren't used for clustering, searching, appraising, etc.

Doing so means a slight loss in e.g. the clustering because the clustering algorithm has less bases on which to make its decision. But, I'd argue there is more advantages to ignoring sequence outside the 60bp window than keeping it, mostly because defining the downstream steps becomes much simpler. For instance, in clustering 60bp sequences we can say that the clusters should have members no more distant than e.g. 5bp across that 60bp region. If we were to include sequences outside the window, then we also have to specify the clustering parameters for alignments outside the sequences (which would probably involve further sequence alignment) e.g. what do we do with two sequences that overlap just across the window and nowhere else?

Also, it is much easier computationally if all sequences are pre-aligned before clustering or searching.

I do have a manuscript in preparation but it isn't ready for public release just yet. If you are super-keen I can give you a look, just let me know.

Hope that explains it.

**Comment by pm-leung** [comment]
Thanks Ben for this detailed explanation! 

I think the use of 60bp window sequence is justified. Now I wonder if this 60bp sequence is a fixed region of a single copy marker, akin to V4-V5 region of 16S. 

If not, I can imagine a situation where this may introduce issues in diversity analysis. Let say, hypothetically, we have a 600 bp marker gene called Marker_A, and reads 1, 2, 3 (150 bp) that are coming from the same species. Read 1 maps to 1-150 bp region of Marker_A, read 2 maps to 151-300 bp region, and read 3 maps to 301-450 bp region. The three reads have no overlapping regions, and thus cannot be clustered. Will SingleM classifies these reads into 3 different OTUs? If yes, it may inflate the diversity observed becuase these OTUs are from the same species. 

Thrilled to know that a manuscript is in preparation, and good luck for that! I am very keen to have a look with the manuscript and think it will help the understanding of the tool, if it is not too much a trouble to you. I will send my email address to you shortly.

Thanks a lot.

**Comment by wwood** [comment]
Hi,

Yes, it is fixed (a fixed position in the HMM). There is a single position for each gene. Even if you define your own singlem packages and put 2 windows in the same gene then they would be treated like different amplicon regions (sort of like if you did a V6-V8 amplicon and then pooled the reads with a V1-V3 amplicon).

Let me know where to send the ms.
ben

**Comment by pm-leung** [comment]
Awesome, problem solved.

**Comment by adityabandla** [comment]
@wwood I would love to understand how the coverage is estimated, if any library depth normalisation is being done. If possible, can you share the draft manuscript for my personal consumption? My id is adityabandla [at] gmail [dot] com

**Comment by wwood** [comment]
Hi,

Coverage is estimated using a formula from the supp material of the velvet paper - basically it is a conversion of kmer coverage to regular coverage. Library size doesn't come into it.

I'll send the paper in prep.
