### ISSUE TITLE
A version update to align with the latest GTDB taxonomy?

### ISSUE THREAD

**Issue by pm-leung** [wwood/singlem#40]
Hi Ben,

I figured out that the taxonomy assignment from SingleM output is using an old version of GTDB taxonomy. For example, the phylum "Bacteroidota" is still "Bacteroidetes" and "Gemmatimonadota" is still "Gemmatimonadetes". I simply fix the issue with some script to change the names. But I am not confident if the taxonomy of lower ranks may also differ significantly from the current GTDB taxonomy. Any plan to update SingleM to align with the lastest GTDB taxonomy? Thanks for developing the tool!

Bob

**Comment by wwood** [comment]
Hi,

Yes, the current taxonomy is based on r86, while the published GTDB taxonomy is r89. It isn't trivial right now to update the taxonomy, unfortunately.

We are working towards expanding the number of marker genes used, and in the process will update the GTDB taxonomy, and streamline the process so it can be automated in the future.

**Comment by pm-leung** [comment]
Good to know! Look forward to future development for both tools.

**Comment by adityabandla** [comment]
@wwood Ben, is there any update to this? I took a stab at creating these new graftM packages for some of the genes using the updated sequences & taxonomy from r89, but currently running into issues at the alignment step when using graftM create

**Comment by wwood** [comment]
Afraid not. I am planning on work on this within the next 3 months, if that helps. Thanks for the continued support. If you are having problems with GraftM maybe raise a ticket on the GraftM github issue tracker, and I'll see what I can do.

**Comment by wwood** [comment]
Hi all,

@rzhao-2 has done this, and put the GTDB r95 packages at https://zenodo.org/record/4325279 - these packages work better than the previous ones in my experience.

To use them, you can unpack the tar.gz and then specify the paths to each spkg with `pipe --singlem_packages`. We couldn't just include them in the code as before because they are too big for PyPI now - we are working on a solution for that.

Thanks for your patience.
ben

**Comment by pm-leung** [comment]
Hi Ben and @rzhao-2 ,

Fantastic news, thank you so much for working on it! It'll be a very useful update. Can I ask are there any obvious differences between the latest packages compared to the previous ones, apart from update and expansion in taxonomy? Before this official update, I attempted to make my own package of the GTDB r95 _rplP_ with the same HMM position windows as the previous version. The issue I experienced when using my own package is the lack of eukaryotic and mitochondrial sequences in GTDB, which leads to some weird classification of sequences to Asgardarchaeota and Rickettsiales. Any ideas on how widespread these single copy prokaryotic ribosomal marker genes in eukaryote and organelles, and how this misclassification is avoided in the latest package?

Many thanks and have a nice holiday break!
Bob

**Comment by wwood** [comment]
Hi Bob,

There are 3 changes I believe - correct me if I'm wrong @rzhao-2 
1) Updated GTDB taxonomy, which is better taxonomy as well as more sequences. OTOH, assignment will take longer because of this, but hope not by much.
2) Updated set of euk sequences that are included in the package. The packages were made with `singlem regenerate --euk_sequences ..` and the sequences that went in there were found from uniprot (as previous, but just with newer data).
3) The HMMs that are used to search for bacterial and archaeal sequences are better, because GTDB is better. The alignment HMMs have not changed though.

Enjoy the holidays.

**Comment by slambrechts** [comment]
Hi Ben and @rzhao-2,

Does this mean these new packages are the preferred way of using `singlem pipe` instead of the regular ones included when installing singlem?

Many thanks for the tool and packages!
Sam

**Comment by wwood** [comment]
Hi Sam,

Yes. I'd say so. We are working on some bigger changes that will appear in the next released version so we haven't put these new pkgs into a release yet.
________________________________
