### ISSUE TITLE
custom database

### ISSUE THREAD

**Issue by housw** [wwood/singlem#49]
Hi Ben, 

this is a feature request instead of a bug report. Would it possible to use my own custom genes? Or can I use database created using `graftM` for `singleM`?

Thanks in advance. 

Best, 
Shengwei

**Comment by wwood** [comment]
Hi,

Thanks for the interest. Yes this is definitely possible. If you supply the `--singlem_packages` flag you can specify paths to one or more singlem packages. This is actually how the testing code works, since using the full set for that is cumbersome.

A singlem package is a graftm package plus a position in the alignment HMM of that graftm package that the window begins. You can create singlem packages using `singlem create`.

Hope that helps, and good luck.
ben

**Comment by wwood** [comment]
Closing now, but happy to reopen if required.
