### ISSUE TITLE
Meaning of Coverage at the OTU Table

### ISSUE THREAD

**Issue by leehwmj** [wwood/singlem#82]
Hello
Thank you for making an excellent program.

As a beginner analyst, I'm asking you this question because I'm curious about using singleM.

After creating the OTUs table, there are several columns, of which 'coverage' is the calculated result, and I wonder where this figure can be used.

You described it as "estimated coverage of a genome from this OTU," but I'm asking you because I don't understand it exactly.

![image](https://user-images.githubusercontent.com/22087964/126020184-53a9a38c-dad1-414d-9a7d-f6f1bdfe9108.png)

In addition, this OTU. When I cluster the csv file, I get the following results, and I wonder why the "sequence" column and the "representative" column are divided when they are the same.

Also, I would appreciate it if you could let me know the meaning of "num_hit", "num_sub_outs", and "max_sub_otu_boundance".
![image](https://user-images.githubusercontent.com/22087964/126020287-d20c957d-1993-464d-94ec-35fb6222e0fe.png)

**Comment by wwood** [comment]
Hi,

Coverage is calculated based on num_hits, which is the number of reads that make up that OTU. Coverage is the expected coverage, where num_hits is the "kmer coverage". If you have a look at the user manual for the velvet manual it gives the precise formula, but it depends on the read length. Actually, I rarely find that column useful, because it is so much easier to use num_hits since it is always an integer.

As for your second question, I believe it is because each OTU is shown as a row in the table. For instance, when 2 sequences are clustered together, but are different, there will be 2 rows, but in only 1 will the sequence equal the representative sequence. I hope that explains it?

Good luck.

**Comment by leehwmj** [comment]
Thank you for your kind explanation.

I have an additional question. In the 10 and 11 columns of the second picture, it says num_sub_otus and max_sub_otu_abundunce, and I wonder what each of them means.

I think it's a question because I don't understand what sub means.

Thanks wwood

**Comment by wwood** [comment]
That's the number of different OTUs that are in the cluster, and the maximal abundance out of those OTUs - make sense?

**Comment by leehwmj** [comment]
Thank you. I fully understand.

I'll close this issue.

**Comment by ellyyuyang** [comment]
Hello Ben,

Thanks for the tool and your explanations! 

I am wondering about your comments on using the **coverage** information after the **condense** function in SingleM for **bacterial/archaeal cell/genome number estimation**? As these 59 single-copy marker genes are assumed to have one copy per genome, ideally using the copy numbers of the single-copy marker genes to imply genome copy number would make sense? (if the coverage in condense singleM output means also marker gene copy numbers)

Also, since there are 35 bacterial and 37 archaeal single-copy marker genes, but add up to a total of 59 different single-copy marker genes, does this mean there are some overlapping bacterial and archaeal single-copy marker genes? Anywhere we can find information regarding these marker genes and how condense function differentiates if a domain-overlapping marker gene is for bacteria or archaea? [I tried to do a bit of research on this, but sorry if I have missed it if this information existed anywhere]

Thanks,
Yu

**Comment by wwood** [comment]
Hi Yu,

Apologies for the lack of documentation on these specifics. A manuscript is in the works.

The `condense` function (or equivalently, `pipe -p` uses several algorithms to convert per-OTU / per-gene / per-taxonmy annotations into a single community profile. It is a little complex but uses expectation-maximisation while respecting the taxonomy of each OTU. The whole process is based upon the taxonomy assignments of each OTU being at least roughly right, but uses trimmed means to avoid nefarious cases.

Yes some genes are shared between Bacteria and Archaea. You can know which is which using `singlem metapackage --describe`.

HTH, ben

**Comment by aljazdzy** [comment]
I was wondering about this too, as my tables for taxonomic units and tables when running the pipe -p function are wildly different.  There's a significant amount of variety that coincides with some 16S I had run separately (albeit, this is showing way more OTUs) that I lose when running pipe -p.  Is there a more accurate way to ascertain the diversity/abundance using the initial non-summarized table output?  I noticed in some of your papers you seem to break it up in number of reads per stretch of conserved amino acid per organism, though I'm a bit of a novice and if I were to get that data from my own samples I'm not quite sure what I would do with it.
