### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by lly10086** [wwood/singlem#91]
1875068 segmentation fault  ExpressBetaDiversity -s 395.otu_table.ebd -c Bray-Curtis，Why does this error appear and how to fix it?

**Comment by wwood** [comment]
Hi,

Unfortunately I cannot really help with this, because  ExpressBetaDiversity is not a part of singlem, but a separate program 
https://github.com/dparks1134/ExpressBetaDiversity

Maybe it would help if you could narrow down whether this is an error with singlem not generating the correct input files, or some error with EBD.

Thanks, ben
